fix: author of single article
pravin/hugo-theme-prav pull request #1
Opened 2020-05-20 12:46 UTC by xiaopengli89

Hi,

This is a pretty nice theme, I like it! I just fix the author of single article.

2020-07-02 21:47 UTC, pravin requested changes
Sorry for the late review! Looks good and thanks for catching a few errors! Thanks for the CSS changes too.

Can you resubmit the PR without the prism changes to custom_header / custom_footer please?

2020-07-02 21:47 UTC, pravin commented on layouts/partials/render_single_article.html
> +    <span class="author">by {{ .Params.author }}</span>
Oops! Thanks :)

2020-07-02 21:47 UTC, pravin commented on layouts/partials/menu.html
> +            <a href="/posts/index.xml" title="Atom Feed" class="pure-menu-link">
Good catch!

2020-07-02 21:47 UTC, pravin commented on layouts/partials/custom_footer.html
> +<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.20.0/prism.min.js"></script>
Are you able to leave this bit out of the PR please as this is custom to how you are using it?

2020-07-03 08:10 UTC, xiaopengli89 commented
Ok, I resubmit the PR.

2020-07-03 08:10 UTC, closed without merging